return {
    "williamboman/mason.nvim",
    opts = {
        ensure_installed = {
            "glint",
            "vtsls",
            "java-debug-adapter",
            "typescript-language-server",
            "shellcheck",
            "tlint",
            "stimulus-language-server",
            "pretty-php",
            "phpstan",
            "pint",
            "intelephense",
            "prettierd",
            "prettier",
            "html-lsp",
            "eslint-lsp",
            "eslint_d",
            "blade-formatter",
            "duster",
            "actionlint",
            "lua-language-server",
            "shfmt",
            "stylua",
            "tailwindcss-language-server",
        },
    },
}
